sudo: required
services:
    - docker

#build test images
before_install:
    - docker build -t neerajchimbili/react-test -f ./client/Dockerfile.dev ./client

#run the tests
script:
    - docker run -e CI=true neerajchimbili/react-test npm run test

#build the prod images
after_success:
    - docker build -t neerajchimbili/multi-react ./client
    - docker build -t neerajchimbili/multi-nginx ./nginx
    - docker build -t neerajchimbili/multi-server ./server
    - docker build -t neerajchimbili/multi-worker ./worker
    #login to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #push the images to the docker hub
    - docker push neerajchimbili/multi-react
    - docker push neerajchimbili/multi-nginx
    - docker push neerajchimbili/multi-server
    - docker push neerajchimbili/multi-worker

deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-553543162824
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY